version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    reviewers:
      - "mrkloan"
    commit-message:
      prefix: "chore"
      prefix-development: "chore(deps)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    merge-policy: "squash"
    auto-merge: true

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "mrkloan"
    commit-message:
      prefix: "chore"
      prefix-development: "chore(deps)"
      include: "scope"
    merge-policy: "squash"
    auto-merge: true