name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2.1.3
        env:
          cache-name: loggia
        with:
          path: ~/.m2/repository
          key: ${{env.cache-name}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            ${{env.cache-name}}-maven
      - name: Run all tests
        run: mvn clean test
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.15
